## Travis CI Integration
language: csharp

solution: HangMan.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore HangMan.sln
after_script:
  - nunit-console Hangman.Tests/bin/Debug/Hangman.Tests.dll