 build_script:
  - mkdir nunit && cd nunit
  - curl https://github.com/nunit/nunit/releases/download/3.0.0-alpha-5/NUnit-3.0.0-alpha-5b.zip -L -o nunit.zip
  - unzip nunit.zip && cd ..
  - nuget install NUnit.Console -Version 3.0.0-alpha-5b -pre
  - nuget restore Hangman/Hangman-4/HangMan.sln
  - msbuild /p:Configuration=Debug Hangman/Hangman-4/HangMan.sln
 test_script:
  - NUnit.Console.3.0.0-alpha-5b\tools\nunit-console-x86.exe Hangman/Hangman.Tests/bin/Debug/Hangman.Tests.dll