before_build:
  - nuget restore Hangman/Hangman-4/HangMan.sln

build_script: 
  - msbuild Hangman/Hangman-4/HangMan.sln /p:Configuration=Release /t:Rebuild
  
  test_script:
  - bin\Release\nunit-console-x86 Hangman/Hangman.Tests/bin/Debug/Hangman.Tests.dll --config=Release